export interface Customer {
  id:number,
  name?:string,
  dateOfBirth?:string,
  gender?:number,
  email?:string,
  address?:string,
  phone?:string,
  identityCard?:string,
  avatar?:string,
  status?:string,
  note?:string,
  Flag?:boolean,
  customerCode?:string,
}
